runtime: nodejs
env: flex
env_variables:
  SQL_USER: root
  SQL_PASSWORD: Andre$23
  SQL_DATABASE: db_master
  INSTANCE_CONNECTION_NAME: app-sarscov2:us-east1:sarscov2db
beta_settings:
  cloud_sql_instances: app-sarscov2:us-east1:sarscov2db